apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: process
spec:
  steps:
    - name: clone-repo                                          #step to clone a Git repository
      image: alpine/git                                         #Docker image with Git CLI
      args:
        - clone                                                 #command to clone the git repository
        - https://github.com/equinor/radix-sub-pipeline-example #the repository to be cloned
        - -b                                                    #clone specific branch
        - pipeline-with-multiple-task-steps                     #the branch to be cloned
        - /var/source/branch                                    #a folder, where to clone the repository
      volumeMounts:
        - name: source-volume                                   #using an empty volume, shared between this task steps
          mountPath: /var/source                                #path, where the common empty volume is mapped

    - name: show-repo                                           #step to process the repository. cloned in the "clone-repo" step
      image: alpine                                             #run a sh-script within a Alpine Linux container
                                                                #"process" the cloned repository - here just show its folder
      script: |
        #!/usr/bin/env sh
        ls -la /var/cloned-repo/branch
        echo "this is hardcoded to release branch"
      volumeMounts:
        - name: source-volume                                   #using the same volume, used in the step "clone-repo"
          mountPath: /var/cloned-repo                           #mount this volume to a folder "/var/cloned-repo"
  volumes:
    - name: source-volume                                       #a volume, which can be shared between task steps
      emptyDir: {}                                              #just an empty volume, being deleted after completion of the task
